### ISSUE TITLE
style sheet not working

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/serviceinnovationlab.github.io#1]
css loads nicely on this page

https://serviceinnovationlab.github.io/reports/2018-06-aotearoa-new-zealand-government-innovation-assets-risks-matti-schneider

but not on other paths such as 
https://serviceinnovationlab.github.io/

**Comment by Br3nda** [comment]
hoping @JacOng17 has time to look at this.

**Comment by JacOng17** [comment]
Just saw this. Will work on this tomorrow morning :)

**Comment by Br3nda** [comment]
Looks like @verbman had a go at it. Can you review and test his work? And see if he's missed anything. https://github.com/ServiceInnovationLab/serviceinnovationlab.github.io/pull/2
