### ISSUE TITLE
Share a provider

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/serviceinnovationlab.github.io#65]
As a user 
I want to be able to share this contact
Because they offer a good service

A / C
 - [ ] Implement AddThis (Node Module)
 - [ ] Should be able to share with Facebook
 - [ ] Should be able to share with Facebook Messenger
 - [ ] Should be able to email the service provider details

**Comment by Br3nda** [comment]
@dlouise64 is this on the wrong repo?
